### ISSUE TITLE
Cant crosscompile

### ISSUE THREAD

**Issue by SolitudeSF** [genotrance/nimarchive#6]
Crosscompiling fails with
```
  ... checking whether we are cross compiling... configure: error: in `/tmp/.cache/nim/nimterop/nimarchive/liblzma':
        ... configure: error: cannot run C compiled programs.
        ... If you meant to cross compile, use `--host'.
```

**Comment by genotrance** [comment]
Nimterop doesn't work with cross-compiling scenarios since Nim itself doesn't support it.

https://github.com/nimterop/nimterop/issues/126

Basically, once you set the target OS to something else, every compile-time call will run as if it is on the target. This breaks many things that nimterop does.

Can you share more details on what you are trying?

**Comment by SolitudeSF** [comment]
im trying to update choosenim for void linux, and it requires package to be built for arm. i guess im gonna mark it as non crosscompilable.

**Comment by genotrance** [comment]
Building for arm using GCC on Linux should still work since the host and target are still posix systems.

How about passing some extra flags to configure? You'd need to edit the package but once you get it working, we can look into making it something that can be detected.

**Comment by SolitudeSF** [comment]
you gonna have to guide me, since im no expert

**Comment by genotrance** [comment]
Catch me on #nim.
